Modified test to run in different browsers and read local variable
Millionhat/AutomationTraining pull request #11
Opened 2022-02-11 21:07 UTC by Millionhat

Local variable named webBrowser

2022-02-11 21:57 UTC, Millionhat reviewed
Added the download action for diferent browsers inside the main.yml, created an environment variable to define which browser to use. The accepted values for the env variable are: edge,firefox,chrome

2022-02-14 19:05 UTC, aperdomob requested changes

2022-02-14 19:05 UTC, aperdomob commented on src/main/java/pages/WebDriverContainer.java
> +    } else if (browser.equalsIgnoreCase("firefox")) {
avoid else if

2022-02-14 19:12 UTC, Millionhat commented on src/main/java/pages/WebDriverContainer.java
> +    } else if (browser.equalsIgnoreCase("firefox")) {
modified to switch case

2022-02-14 19:30 UTC, aperdomob approved these changes

2022-02-14 19:30 UTC, merged