created WebDriverContainer that will serve as a universal access for …
Millionhat/AutomationTraining pull request #9
Opened 2022-01-25 21:26 UTC by Millionhat

…the pages

2022-01-28 20:04 UTC, kliver98 commented on src/main/java/pages/WebDriverContainer.java
> + * Class in charge of storing the webDriver for an easy access to the Page classes.
```suggestion
 * Class in charge of storing the webDriver for easy access to the Page classes.
```

2022-01-28 20:04 UTC, kliver98 commented on src/main/java/pages/WebDriverContainer.java
> +    }
Why don't just have one driver == null verification?

2022-01-28 20:04 UTC, kliver98 commented on src/main/java/pages/WebDriverContainer.java
> +  public void quitDriver() {
Defined but never called

2022-01-28 20:06 UTC, kliver98 commented on src/test/java/BuyTshirtProcessTest.java
> +  private WebDriver wdc;
please use a descriptive name not just `wdc`

2022-01-28 20:09 UTC, kliver98 commented on src/test/java/BuyTshirtProcessTest.java
> +    //wdc.close();
this should be commented? this method is not doing nothing

2022-02-07 11:48 UTC, aperdomob requested changes

2022-02-07 11:48 UTC, aperdomob commented on src/main/java/pages/GooglePage.java
> -  private WebDriver driver;
you don't need remove this variable

2022-02-07 11:48 UTC, aperdomob commented on src/test/java/BuyTshirtProcessTest.java
> +    driver = WebDriverContainer.getInstance();
why do you need this instance here

2022-02-09 17:12 UTC, aperdomob approved these changes

2022-02-09 17:12 UTC, merged